#!/bin/bash
# 网易云签到、打卡shell脚本自用

# 手机号
phone="$1"
# 密码或md5
pass="$2"
# server 酱
server="$3"

api='https://163.newlover.cn/api.php?do'

# 预处理

if [ $(echo ${#pass}) == 32 ]
then
md5="$2"
else
md5=$(echo -n $pass | md5sum | cut -d ' ' -f1)
fi

# 登录并获取cookie
r=0.12441054$(date +%N)
post="uin=$phone&pwd=$md5&r=$r"
cookie=$(curl -s $api=login -d $post -c - | sed '/FALSE/!d;s/.*\W0\W//g;s/\W/=/g' | xargs | sed 's/ /;/')


# 签到
r=0.12441054$(date +%N)
curl -s $api=sign -b $cookie -d r=$r | grep "签到" && (echo "签到成功！" ; curl -s "https://sc.ftqq.com/$server.send" -d "text=网易云签到成功") || (echo "签到失败！" ; curl -s "https://sc.ftqq.com/$server.send" -d "text=网易云签到失败")

# 打卡
r=0.12441054$(date +%N)
curl -s $api=daka -b $cookie -d r=$r | grep "200" && echo "听歌成功！" || echo "听歌失败！"
